### ISSUE TITLE
Convert To Image

### ISSUE THREAD

**Issue by thingsofleon** [alsauve/scaleogram#7]
Maybe I just don't know how to do this, but I am looking into using this package for Machine Learning. I was wondering if there was a way to convert the plot to an image.
It is so wonderful that you have made this so easy to a view the plots!
I think if we can get a away to use this to create datasets for ML/DL, that would be huge!

**Comment by Olivier-tl** [comment]
You can do the following to save an image of the plot without the frame and axes, only the content: 
```
ax = scg.cws(..., coi=False, title='', cbar=None)
ax.set_axis_off()
plt.savefig('out.png', bbox_inches='tight', pad_inches=0)
```
For ML/DL, you can also use the argument `scg.cws(cmap='Greys')` so that the scaleogram is in grayscales!

**Comment by alsauve** [comment]
The comment og @Olivier-tl is indeed the way to do this.

I close the issue.
